config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :users
  resources :vendors
=begin    
    get "/vendors" index
    post "/vendors" create
    delete "/vendors/:id" delete
    get "/vendors/:id" show
    get "/vendors/new" new
    get "/vendors/:id/edit" edit
    patch "/vendors/:id" update
    put "/vendors/:id" update
=end

  resources :orders
=begin    
    get "/orders" index
=end

get 'welcome/index'
root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :vendor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :vendors
end

app/models/vendor.rb
class Vendor < ApplicationRecord
	has_many :orders
	belongs_to :user
	validates :name, presence: true, uniqueness: true
	validates :address, presence: true, length: {minimum: 10}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

before_action :authenticate_user!

  #GET /orders
	def index
		@orders = Order.paginate(page: params[:page],per_page: 20).all.order(:created_at)
		calculate_deliveries
	end
	
	#GET /orders/:id
	def show
		@order = Order.find(params[:id])
	end
	
	# GET /orders/new
	def new
		@order = Order.new
	end

	def edit
		@order = Order.find(params[:id])
	end

	# POST /orders
	def create
		#@order = Order.new(name: params[:Order][:name],address: params[:Order][:address])
		@order = Order.new(order_params)
		
		if @order.save
			redirect_to @order
		else
			render :new
		end
	end

	def destroy
		@order = Order.find(params[:id])
		@order.destroy
		redirect_to orders_path
	end

	#PUT /orders/:id
	def update
		@order = Order.find(params[:id])
		if @order.update(order_params)
			redirect_to @order
		else
			render :edit
		end

	end 

	private

	def order_params
		params.require(:order).permit(:name,:tracking_number,:address,:order_number,:vendor_id)
	end


	#HardWorker.perform_async('bob', 5)


	def calculate_deliveries
		@orders.each do |i|

		 a = DateTime::now 
		 b = DateTime.new(i.created_at.year.to_i,i.created_at.month.to_i,i.created_at.day.to_i,i.created_at.hour.to_i,i.created_at.min.to_i,i.created_at.sec.to_i,'-5')
         
         diff = a.to_time - b.to_time
         
         minutes_from_created = diff / 60

         if minutes_from_created > 0 
	         if minutes_from_created < 720 #12 hours
	         	i.update_attribute(:message, 'Normal')
	         	i.update_attribute(:time_min, minutes_from_created)
	         elsif minutes_from_created < 1440 #24 hours
	         	i.update_attribute(:message, 'Not Normal')
	         	i.update_attribute(:time_min, minutes_from_created)
	         else 
	         	if minutes_from_created > 1440 
		         	# more than 24 hrs
		         	i.update_attribute(:message, 'Very Late')
		         	i.update_attribute(:time_min, minutes_from_created)
	         	end
			end
		else
			i.update_attribute(:message, 'Processing')
		    i.update_attribute(:time_min, 0)
		end
	end
	end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
	
	before_action :authenticate_user!


	#GET /vendors
	def index
		@vendors = Vendor.paginate(page: params[:page],per_page: 20).all

	end
	
	#GET /vendors/:id
	def show
		@vendor = Vendor.find(params[:id])
	end
	
	# GET /vendors/new
	def new
		@vendor = Vendor.new
	end


	def edit
		@vendor = Vendor.find(params[:id])
	end

	# POST /vendors
	def create
		#@vendor = Vendor.new(name: params[:vendor][:name],address: params[:vendor][:address])
		@vendor = current_user.vendors.new(vendor_params)
		
		if @vendor.save
			redirect_to @vendor
		else
			render :new
		end
	end

	def destroy
		@vendor = Vendor.find(params[:id])
		@vendor.destroy
		redirect_to vendors_path
	end

	#PUT /vendors/:id
	def update
		@vendor = Vendor.find(params[:id])
		if @vendor.update(vendor_params)
			redirect_to @vendor
		else
			render :edit
		end

	end 

	private

	def vendor_params
		params.require(:vendor).permit(:name,:address)
	end

	#OrdersNotifierJob.perform_later 'Hi'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Negotiatus</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
        <% if user_signed_in?%>  
          <div class="start">
                <%= render "partials/navigation"%>
                <main>
                  <div class="helper">
                    <p class="notice"><%= notice %></p>
                    <p class="alert"><%= alert %></p>
                    <%= yield %>
                  </div>
                </main>
          </div>
          <%else%>
          <div class="nostart">
                <main>
                  <div class="helper">
                    <p class="notice"><%= notice %></p>
                    <p class="alert"><%= alert %></p>
                    <%= yield %>
                  </div>
                </main>
          </div>
          <%end%>      
</body>
</html>

app/views/orders/_form.html.erb
<h1><%= name%></h1>
<%= form_for(@order) do |f| %>
<% @order.errors.full_messages.each do |message| %>
<div> <%= message%></div>
<%end %>
<div class="form-style-6">
<div>
	<%= f.text_field :order_number, placeholder: "Order number"%>
</div>
<div>
	<%= f.text_field :tracking_number, placeholder: "Tracking number"%>
</div>
<div>
	<%= f.text_field :address, placeholder: "Address"%>
</div>
<div>
	<%= f.collection_select(:vendor_id, Vendor.all, :id, :name) %>
</div>
	<%= f.submit "Save" , class:"add-button"%>
<button class="add-button">
	<%= link_to("Cancel",{action:"index"}) %>
</button> 
	
</div>

<%end%>
</div>

app/views/orders/_no_orders_delivered.html.erb
No delivered

app/views/orders/_packages_late.html.erb
Packages are arriving late 

app/views/orders/index.html.erb
<h1>Orders list</h1>
<div>
	
<button class="add-button">
<%= link_to("Add order",{action:"new"}) %>
</button>
</div>
<br>

<div>
	<table>
		<thead>
			<tr>
				<th>Tracking number</th>
				<th>Order number</th>
				<th>Address</th>
				<th>Minutes shipment</th>
				<th>Status</th>
				<th>Vendor</th>
				
			</tr>
		</thead>
		<tbody>
		<% @orders.each do |order|  %>
			<tr>
				<td><%= order.tracking_number%></td>
				<td><%= order.order_number%></td>
				<td><%= order.address%></td>
				<td><%= order.time_min%></td>
				<% if order.message.eql? 'Normal' %>
				<td class="normal"><%= order.message%></td>
				<%end%>
				<% if order.message.eql? 'Not Normal' %>
				<td class="notdanger"><%= order.message%></td>
				<%end%>
				<% if order.message.eql? 'Very Late' %>
				<td class="danger"><%= order.message%></td>
				<%end%>
				<% if order.message.eql? 'Processing' %>
				<td ><%= order.message%></td>
				<%end%>
				<td><%= order.vendor.name%></td>
			</tr>
		<%end%>
		</tbody>
	</table>
</div>
<%= will_paginate @orders%>

app/views/orders/new.html.erb
<%= render "orders/form", name:"Create new order" %>

app/views/orders/show.html.erb
<h1>Detail Order</h1>
<%= link_to("<<back Orders",{action:"index"}) %>
<table>
		<thead>
			<tr>
				<th>Tracking number</th>
				<th>Order number</th>
				<th>Address</th>
				<th>Vendor</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
				<%= @order.tracking_number %>
			</td>
			<td>
				<%= @order.order_number %>
			</td>
			<td>
				<%= @order.address %>
			</td>
			<td>
				<%= @order.vendor.name %>
			</td>
			
			</tr>
	
			
		</tbody>
	</table>

app/views/partials/_navigation.html.erb
<nav class="menu" tabindex="0">
	<div class="smartphone-menu-trigger"></div>
  <header class="avatar">
		
    <% if user_signed_in?%>
    <img src="https://yt3.ggpht.com/-dXbXqdhSJZ8/AAAAAAAAAAI/AAAAAAAAAAA/mo57E5pG3TQ/s100-c-k-no-mo-rj-c0xffffff/photo.jpg" />
    <h2>Diego F. Ruiz S.</h2>
    <%=current_user.email%>
      <button class="danger-button">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </button>
    
    <% else%>
      <button class="add-button">
        <%= link_to "Sign In", new_user_session_path%>
      </button>
      <button class="edit-button">
        <%= link_to "Sign Up", new_user_registration_path%>
      </button>
    <%end%>
  </header>
	<ul>
    <li tabindex="0" class="icon-dashboard"><span><%= link_to "Dashboard", root_path%></span></li>
    <li tabindex="0" class="icon-orders"><span><%= link_to "Orders", orders_path%></span></li>
    <li tabindex="0" class="icon-vendors"><span><%= link_to "Vendors", vendors_path%></span></li>
  </ul>
</nav>

app/views/vendors/_form.html.erb
<h1><%= name%></h1>
<%= form_for(@vendor) do |f| %>
<% @vendor.errors.full_messages.each do |message| %>
<div> <%= message%></div>
<%end %>
<div class="form-style-6">

<div>
	<%= f.text_field :name, placeholder: "Name"%>
</div>
<div>
	<%= f.text_field :address, placeholder: "Address"%>
</div>
	<%= f.submit "Save" , class:"add-button"%>
<button class="add-button">
	<%= link_to("Cancel",{action:"index"}) %>
</button> 
	
</div>

<%end%>
</div>

app/views/vendors/edit.html.erb
<%= render "vendors/form", name: "Edit Vendor" %>

app/views/vendors/index.html.erb
<h1>Vendors list</h1>
<div>
	
<button class="add-button">
<%= link_to("Add vendor",{action:"new"}) %>
</button>
</div>
<br>

<div>
	<table>
		<thead>
			<tr>
				<th>Name</th>
				<th>Address</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
		<% @vendors.each do |vendor|  %>
			<tr>
				<td><%= link_to vendor.name, vendor%></td>
				<td><%=vendor.address%></td>
				<td>
					<button class="danger-button">
					<%= link_to "Delete", vendor,method: :delete %>
					</button>
						
					</td>

			</tr>
		<%end%>
		</tbody>
	</table>
</div>
	
<%= will_paginate @vendors%>

app/views/vendors/new.html.erb
<%= render "vendors/form", name:"Create Vendor" %>

app/views/vendors/show.html.erb
<h1>Detail Vendor</h1>
<%= link_to("<<back Vendors",{action:"index"}) %>
<table>
		<thead>
			<tr>
				<th>Name</th>
				<th>Address</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
	
			<tr>
			<td>
				<%= @vendor.name %>
			</td>
			<td>
				<%= @vendor.address %>
			</td>
			<td>
				<button class="edit-button">
					
				<%= link_to "Edit", edit_vendor_path(@vendor)%>			
				</button>
			</td>	
			</tr>
	
			
		</tbody>
	</table>

app/views/welcome/index.html.erb
  <% if user_signed_in?%> 
  <h1>Welcome to tracking dashboard web app</h1>
  <fieldset>
  	<span>Not-delivered orders</span>
  	<%= render 'orders/no_orders_delivered'%>
  </fieldset>
  <fieldset>
  	<span>Arriving late</span>
  	<%= render 'orders/packages_late'%>
  </fieldset>
  <%else%>
<div class="login-page">
<h1>Welcome to tracking dashboard web app</h1>
  <div class="form">
      	<% if user_signed_in?%>
      	<% else%>
        <button>
        <%= link_to "Sign In", new_user_session_path%>
        </button>
        <button>
        <%= link_to "Sign Up", new_user_registration_path%>
        </button>
		<%end%>
  </div>
</div>
<%end%>